//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over ons.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlleTickets.
        /// </summary>
        public static string AlleTickets {
            get {
                return ResourceManager.GetString("AlleTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toont een lijst van alle bestaande tickets..
        /// </summary>
        public static string AlleTicketsmsg {
            get {
                return ResourceManager.GetString("AlleTicketsmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuis.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw ticket.
        /// </summary>
        public static string NieuwTicket {
            get {
                return ResourceManager.GetString("NieuwTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een nieuw ticket aan in het systeem..
        /// </summary>
        public static string NieuwTicketmsg {
            get {
                return ResourceManager.GetString("NieuwTicketmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportCenter.
        /// </summary>
        public static string SupportCenter {
            get {
                return ResourceManager.GetString("SupportCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticketnummer.
        /// </summary>
        public static string Ticketnummer {
            get {
                return ResourceManager.GetString("Ticketnummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon ticket.
        /// </summary>
        public static string ToonTicket {
            get {
                return ResourceManager.GetString("ToonTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geeft de details van één ticket..
        /// </summary>
        public static string ToonTicketmsg {
            get {
                return ResourceManager.GetString("ToonTicketmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom op het online helpdesk systeem..
        /// </summary>
        public static string Welkom {
            get {
                return ResourceManager.GetString("Welkom", resourceCulture);
            }
        }
    }
}
